### ISSUE TITLE
ActiveRecord connection pool stats

### ISSUE THREAD

**Issue by mikz** [yabeda-rb/yabeda-rails#4]
ActiveRecord exposes statistics about its' connection pool. Would you be interested in exposing those? I took a quick stab at it in one project: https://github.com/3scale/zync/pull/181/commits/41f4cb6ee472896a4a94cdcd5ee92a90b9bf15ba

**Comment by Envek** [comment]
Yes! Absolutely interested and will implement this (and some more things like query timings and counters). 

But I think that it should go to the separate gem like `yabeda-activerecord` because not everyone who uses Rails are using ActiveRecord and not everyone who uses ActiveRecord uses Rails (e.g. Sinatra with AR was quite common for small apps long ago)

I hope I will find time for this soon

**Comment by mikz** [comment]
That is a very good point 👍  But possibly `yabeda-rails` should still depend on `yabeda-activerecord` like rails does, so it works out of the box. And enable itself only when `ActiveRecord::Base` is defined.

**Comment by Envek** [comment]
I procrastinated for more than 3 years (sorry!) and finally I forced myself to make it. Please enjoy: https://github.com/yabeda-rb/yabeda-activerecord
